### ISSUE TITLE
Email Obfuscation Edit 

### ISSUE THREAD

**Issue by HitokageTaka** [InQuest/python-iocextract#22]
Identify and 'refang' emails formatted as follows:
identifier[@]domain[.com]

**Comment by rshipp** [comment]
Thanks for the issue! This should be doable.

If you don't mind me asking, where are you seeing emails in this format?

**Comment by HitokageTaka** [comment]
Thank you for the quick reply! In an information sharing group my
organization is a part of. I could probably provide you with 100 different
“defanging” techniques these analysts try.

Another for your consideration could be another common defang technique of
“google DOT com”. They will literally type “dot” or “at” rather than a [.]
or [@].

Again thanks for the prompt reply!

**Comment by rshipp** [comment]
Interesting, thanks. If you have more defangs we're not catching, definitely feel free to share them. 

I'll try to up the robustness of our email support in general. It's a bit weaker than our URL support just because I don't often see emails shared, and didn't realize it was something people needed.

**Comment by rshipp** [comment]
Just published [v1.10.0](https://github.com/InQuest/python-iocextract/releases/tag/v1.10.0) to PyPI, that should catch everything you mentioned and more.

Let me know if there are any that still don't get picked up, or any false positives/other issues!
