### ISSUE TITLE
ModuleNotFoundError: No module named 'iocextract'

### ISSUE THREAD

**Issue by ZeroDot1** [InQuest/python-iocextract#71]
I installed it in Arch Linux, unfortunately I only get an error message.

Steps: 

```py
sudo pipx install iocextract --force
iocextract -h

```
```py
$ /usr/bin/iocextract -h
Traceback (most recent call last):
  File "/usr/bin/iocextract", line 5, in <module>
    from iocextract import main
ModuleNotFoundError: No module named 'iocextract'

```

**Comment by DragonistYJ** [comment]
您好，我已经收到您的周报，周报收取截止时间为每周二下午八点，八点后将截止收取，请按时发送您的周报，谢谢！

**Comment by azazelm3dj3d** [comment]
Hi, @ZeroDot1!

When importing the iocextract module, you don't need to specify the main method. The `main()` method is reserved for using the project as a command line interface (CLI) and is already configured without the need to import.

If you're trying to use the CLI, all you need to do is install the package from pip(x) and run the project directly from the terminal, like so:

```bash
iocextract -h
```

You do not need to write your own script to use the module. If you cannot locate your installation, your PATH may need to be configured for pip(x) installations.

I also noticed you installed the module using `sudo`. This means your script (or if you're using it as a CLI) may not be able to find the module since it's not installed for your local user.

I use a flavor of Arch Linux as one of my primary host systems and I've had no issues running this module in the past, so I don't think that would be the issue. It's most likely a local misconfiguration or permissions issue from using escalated privileges to install the module.

If you're still experiencing issues, feel free to let me know. Based on the information provided, I believe you may just need to update how you're using the module locally.

I would also recommend checking out the iocextract documentation here: https://inquest.readthedocs.io/projects/iocextract/en/latest/

If you would like to use it as a library, all you have to do is import the module. Here's an example:

```python
import iocextract

def extract_content():
    content = \
    """
    Check out hxxps://inquest[.]net
    """

    for i in iocextract.extract_iocs(content):
        print(i)

if __name__ == '__main__':
    extract_content()
```
