### ISSUE TITLE
Add a function to import directly from a server and extract IOCs.

### ISSUE THREAD

**Issue by ZeroDot1** [InQuest/python-iocextract#74]
Example` iocextract --input 'https://toast.home.us/random' --output '/home/user/k1.txt' --extract-ipv4s`

**Comment by azazelm3dj3d** [comment]
Hi, @ZeroDot1

Due to how the `--input` argument is currently configured, I decided to create a separate argument to allow for a quicker resolution. You can find the command below, which should pull down the IOCs, extract the data from the file, and save them to `k1.txt`.

```bash
iocextract -ri --url 'https://toast.home.us/random' --output '/home/user/k1.txt' --extract-ipv4s
```

Once the new version is available, you can run the following command to update your installation:
```bash
pip install iocextract -U
```

**Comment by azazelm3dj3d** [comment]
@ZeroDot1 I wanted to ping you to let you know the new version is now available!

PyPI: https://pypi.org/project/iocextract/1.16.0/
Release: https://github.com/InQuest/iocextract/releases/tag/v1.16.0
